#!/bin/bash
BUILD=./target/antlr4
mkdir -p $BUILD
cp ./app/src/main/antlr4/Liquid.g4 $BUILD
export CLASSPATH=".:/usr/local/lib/antlr-4.5.3-complete.jar:$CLASSPATH"
java -Xmx500M -cp "/usr/local/lib/antlr-4.5.3-complete.jar:$CLASSPATH" org.antlr.v4.Tool $BUILD/Liquid.g4
cd $BUILD
javac *.java
